'use client'

import { useState, useEffect } from 'react'
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Loader2, BrainCircuit, Check, X, ThumbsUp, ThumbsDown, MessageSquare, CheckCircle2, ArrowLeft } from 'lucide-react'
import { toast } from 'sonner'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import Link from 'next/link'

interface AIDecision {
  id: string
  action_type: string
  target_id: string
  ai_rationale: string
  confidence_score: number
  status: string
  created_at: string
  source_module: string
  expected_impact?: string
}

export default function UnifiedDecisionCenter() {
  const [decisions, setDecisions] = useState<AIDecision[]>([])
  const [loading, setLoading] = useState(true)
  const [feedback, setFeedback] = useState('')
  const [activeDecisionId, setActiveDecisionId] = useState<string | null>(null)

  useEffect(() => {
    fetchDecisions()
  }, [])

  const fetchDecisions = async () => {
    setLoading(true)
    try {
      const res = await fetch("/api/decisions")
      const data = await res.json()
      if (data.success && data.decisions) {
        setDecisions(data.decisions)
      }
    } catch (err) {
      console.error("Failed to fetch AI decisions:", err)
    } finally {
      setLoading(false)
    }
  }

  const handleAction = async (id: string, action: 'APPROVE' | 'REJECT') => {
    try {
      await fetch("/api/decisions", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id, action }),
      })
      toast.success(`Action successfully ${action.toLowerCase()}ed and dispatched.`)
      setDecisions(prev => prev.map(d => d.id === id ? { ...d, status: action === 'APPROVE' ? 'APPROVED' : 'REJECTED' } : d))
    } catch {
      toast.error("Failed to dispatch decision action")
    }
  }

  const submitFeedback = async (type: 'HELPFUL' | 'NOT_HELPFUL') => {
    toast.success(`Feedback logged to Knowledge Base: ${type}`)
    setFeedback('')
    setActiveDecisionId(null)
  }

  return (
    <div className="p-6 space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div className="flex items-center gap-4">
          <Link href="/meta-ads">
            <Button variant="ghost" size="icon">
              <ArrowLeft className="w-5 h-5" />
            </Button>
          </Link>
          <div>
            <h2 className="text-2xl font-bold tracking-tight">Unified AI Decision Center</h2>
            <p className="text-muted-foreground text-sm">Approve cross-platform actions generated by the Enterprise Intelligence Engine.</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <Badge variant="outline" className="bg-emerald-50 dark:bg-emerald-500/10 text-emerald-700 dark:text-emerald-400 border-emerald-200 dark:border-emerald-500/20">
            <CheckCircle2 className="w-3 h-3 mr-1" /> Governance Active
          </Badge>
        </div>
      </div>

      {loading ? (
        <div className="flex justify-center p-12"><Loader2 className="w-8 h-8 animate-spin text-muted-foreground" /></div>
      ) : (
        <div className="space-y-4">
          {decisions.map(decision => (
            <Card key={decision.id} className="overflow-hidden border-indigo-100 dark:border-indigo-900/30">
              <div className="flex flex-col md:flex-row">
                {/* Left side: Status & Core Info */}
                <div className="bg-muted/30 dark:bg-muted/10 p-6 md:w-1/3 border-r">
                  <div className="flex items-center gap-2 mb-4">
                    <BrainCircuit className="w-5 h-5 text-indigo-600" />
                    <span className="font-semibold">{decision.action_type}</span>
                  </div>
                  <div className="space-y-3">
                    <div>
                      <Label className="text-xs text-muted-foreground">Source Intelligence</Label>
                      <p className="font-medium text-sm flex items-center">
                        <Badge variant="outline" className="bg-background">{decision.source_module}</Badge>
                      </p>
                    </div>
                    <div>
                      <Label className="text-xs text-muted-foreground">AI Confidence</Label>
                      <p className="font-medium text-emerald-600">{decision.confidence_score}%</p>
                    </div>
                    <div>
                      <Label className="text-xs text-muted-foreground">Status</Label>
                      <div className="mt-1">
                        <Badge variant={decision.status === 'PENDING_APPROVAL' ? 'secondary' : decision.status === 'REJECTED' ? 'destructive' : 'default'}>
                          {decision.status}
                        </Badge>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Right side: Explainable AI & Actions */}
                <div className="p-6 md:w-2/3 flex flex-col justify-between">
                  <div className="space-y-4">
                    <div>
                      <Label className="text-xs text-muted-foreground">Target / Topic</Label>
                      <h4 className="font-semibold text-lg">{decision.target_id}</h4>
                    </div>
                    <div>
                      <Label className="text-xs text-muted-foreground">Explainable AI Rationale</Label>
                      <p className="text-sm mt-1 bg-indigo-50/50 dark:bg-indigo-900/10 p-4 rounded-md border border-indigo-100/50 dark:border-indigo-900/30 leading-relaxed">
                        {decision.ai_rationale}
                      </p>
                    </div>
                    
                    {decision.expected_impact && (
                      <div className="flex items-center gap-2 text-sm text-emerald-700 dark:text-emerald-400 bg-emerald-50 dark:bg-emerald-500/10 p-2 rounded border border-emerald-100 dark:border-emerald-500/20 w-max">
                        <strong>Expected Impact:</strong> {decision.expected_impact}
                      </div>
                    )}
                  </div>

                  <div className="mt-6 flex flex-wrap items-center gap-3">
                    {decision.status === 'PENDING_APPROVAL' && (
                      <>
                        <Button onClick={() => handleAction(decision.id, 'APPROVE')} className="bg-indigo-600 hover:bg-indigo-700 text-white">
                          <Check className="w-4 h-4 mr-2" /> Approve & Dispatch
                        </Button>
                        <Button variant="outline" onClick={() => handleAction(decision.id, 'REJECT')} className="text-red-600 dark:text-red-400 hover:text-red-700 dark:hover:text-red-300 hover:bg-red-50 dark:hover:bg-red-900/20">
                          <X className="w-4 h-4 mr-2" /> Reject Action
                        </Button>
                      </>
                    )}

                    <Dialog open={activeDecisionId === decision.id} onOpenChange={(open) => !open && setActiveDecisionId(null)}>
                      <DialogTrigger className="inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 border border-input bg-background hover:bg-accent hover:text-accent-foreground h-9 px-4 py-2 ml-auto" onClick={() => setActiveDecisionId(decision.id)}>
                        <MessageSquare className="w-4 h-4 mr-2" /> Train AI
                      </DialogTrigger>
                      <DialogContent>
                        <DialogHeader>
                          <DialogTitle>Knowledge Base Feedback</DialogTitle>
                        </DialogHeader>
                        <div className="space-y-4 py-4">
                          <p className="text-sm text-muted-foreground">
                            Your feedback helps the Enterprise AI learn. This will be stored in the Knowledge Base for future cross-platform decisions.
                          </p>
                          <Textarea 
                            placeholder="e.g., Rejecting because we are out of stock right now..." 
                            value={feedback}
                            onChange={(e) => setFeedback(e.target.value)}
                          />
                          <div className="flex gap-2 justify-end">
                            <Button variant="outline" className="text-red-600 dark:text-red-400 hover:text-red-700 dark:hover:text-red-300 hover:bg-red-50 dark:hover:bg-red-900/20" onClick={() => submitFeedback('NOT_HELPFUL')}>
                              <ThumbsDown className="w-4 h-4 mr-2" /> Bad Recommendation
                            </Button>
                            <Button variant="outline" className="text-emerald-600 dark:text-emerald-400 hover:text-emerald-700 dark:hover:text-emerald-300 hover:bg-emerald-50 dark:hover:bg-emerald-900/20" onClick={() => submitFeedback('HELPFUL')}>
                              <ThumbsUp className="w-4 h-4 mr-2" /> Good Recommendation
                            </Button>
                          </div>
                        </div>
                      </DialogContent>
                    </Dialog>
                  </div>
                </div>
              </div>
            </Card>
          ))}
        </div>
      )}
    </div>
  )
}
